name: taxi_driver
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # TOAST
  fluttertoast: 8.2.6

  # IMAGE
  cached_network_image: ^3.3.1
  firebase_app_check: ^0.3.0+4

  # BASE
  intl: ^0.17.0
  google_fonts: ^6.2.1
  html: ^0.15.4
  shared_preferences: ^2.2.3
  flutter_widget_from_html: ^0.15.1
  flutter_local_notifications: ^17.2.2
  # UI
  sliding_up_panel: ^2.0.0+1
  dotted_line: ^3.2.2
  lottie: ^3.1.2
  flutter_rating_bar: ^4.0.1
  flutter_staggered_animations: ^1.1.1
  bottom_picker: ^2.8.0
  country_code_picker: ^3.0.0
  flutter_native_contact_picker: ^0.0.6
  timeline_tile: ^2.0.0
  flutter_vector_icons: ^2.0.0
  flutter_switch: ^0.3.2
  syncfusion_flutter_charts: ^20.3.61
  google_maps_place_picker_mb: ^3.1.2
  #OTP TEXTFIELD
  otp_text_field: ^1.1.3

  # MAP
  geolocator: ^10.0.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.7.0
  flutter_polyline_points: ^2.1.0
  location: ^7.0.0

  # IMAGES
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  date_time_picker: ^2.1.0
  sms_autofill: ^2.4.0
  # CONNECTIVITY
  package_info_plus: ^8.0.0


  # CONNECTIVITY
  http: ^1.2.2
  connectivity_plus: ^5.0.0
  url_launcher: ^6.3.0

  #FIREBASE
  firebase_crashlytics: ^4.0.2
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.1
  firebase_storage: ^12.1.0
  firebase_database: ^11.0.2
  paginate_firestore: ^1.0.0
  cloud_firestore: ^5.1.0

#  firebase_crashlytics: ^3.0.11
#  firebase_core: ^2.4.1
#  firebase_auth: ^4.2.5
#  firebase_storage: ^11.0.10
#  firebase_database: ^10.0.9
#  paginate_firestore: ^1.0.3+1
#  cloud_firestore: ^4.3.1



  # STATE MANAGEMENT
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  # Payment gateway
  razorpay_flutter: ^1.3.7
  flutter_stripe: ^10.2.0

  flutter_braintree: ^4.0.0
  flutterwave_standard: ^1.0.8
  flutter_paytabs_bridge: ^2.6.14
  my_fatoorah: ^3.3.0
  paytm: ^3.0.1


  # PUSH NOTIFICATION
  onesignal_flutter: ^3.5.0

  # Social Login
  google_sign_in: ^6.2.1

  # MQTT
  mqtt_client: ^10.0.0

  # DOWNLOAD INVOICE PDF
  pdf: ^3.11.0
  path_provider: ^2.1.3
  open_file: ^3.3.2
  printing: ^5.13.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs
dependency_overrides:
  firebase_core_platform_interface: ^5.0.1
  intl: ^0.18.0
  package_info_plus: ^8.0.0
  ffi: ^2.0.1
  open_file: 3.3.2
  cloud_firestore: ^5.1.0

flutter:

  uses-material-design: true


  assets:
      - images/
      - images/icons/
      - images/flag/
