// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS_ddcwlsSb7hzavsPaHzlt0xhr7y-8_4',
    appId: '1:706231173089:android:1c9173b54d65e550309ca0',
    messagingSenderId: '706231173089',
    projectId: 'eshhun-51b68',
    storageBucket: 'eshhun-51b68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8YjaF-CQ3CaRVHrXE6mbS7QAe6gF3OA0',
    appId: '1:706231173089:ios:b193ff073fdb5442309ca0',
    messagingSenderId: '706231173089',
    projectId: 'eshhun-51b68',
    storageBucket: 'eshhun-51b68.appspot.com',
    iosBundleId: 'com.eshhun',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxcsPOlwwu3niBm_5tUvQlfD4cpLWAvwE',
    appId: '1:706231173089:web:3e3390177dd82741309ca0',
    messagingSenderId: '706231173089',
    projectId: 'eshhun-51b68',
    authDomain: 'eshhun-51b68.firebaseapp.com',
    storageBucket: 'eshhun-51b68.appspot.com',
    measurementId: 'G-MDX4BL2DJ4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8YjaF-CQ3CaRVHrXE6mbS7QAe6gF3OA0',
    appId: '1:706231173089:ios:b193ff073fdb5442309ca0',
    messagingSenderId: '706231173089',
    projectId: 'eshhun-51b68',
    storageBucket: 'eshhun-51b68.appspot.com',
    iosBundleId: 'com.eshhun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxcsPOlwwu3niBm_5tUvQlfD4cpLWAvwE',
    appId: '1:706231173089:web:dc563645d910bcf5309ca0',
    messagingSenderId: '706231173089',
    projectId: 'eshhun-51b68',
    authDomain: 'eshhun-51b68.firebaseapp.com',
    storageBucket: 'eshhun-51b68.appspot.com',
    measurementId: 'G-GJ0B6DDFFK',
  );

}